version: '3.9'
services:
  app:
    image: customtutor
    build: .
    env_file:
      - .env
    ports:
      - "8501:8501"
    stdin_open: true
    tty: true
    restart: always
    command: pipenv run streamlit run Home.py --server.port 8501